name: Rust

on: [push]

jobs:
  test_Windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build unicorn engine
      run: |
        git clone https://github.com/unicorn-engine/unicorn unicorn_engine
        cd unicorn_engine
        mkdir build; cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        nmake

    - name: Install build tool
      run: |
        cargo install cargo-c
        mkdir build

    - name: Build udbserver
      run: |
        mkdir win
        cargo cinstall --release --prefix=win --destdir build

    - name: List Files
      run: |
        cd build
        dir

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: build\
