name: Rust

on: [push]

jobs:
  test_Windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Enable NMake
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install build tool
      run: |
        cargo install cargo-c
        mkdir build

    - name: Build udbserver
      run: |
        mkdir win
        cargo cinstall --release --prefix=win --destdir build

    - name: List Files
      run: |
        dir build

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build/

    - name: Setup Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.9.7
    
    - name: Install venv
      run: |
        cd bindings\python
        pip install virtualenv
        python -m venv pbind
        pbind\Scripts\activate.bat
        python setup.py build
        python setup.py install

    - uses: actions/upload-artifact@v3
      with:
        name: python-binding
        path: ./bindings/python/
